// Copyright 2008-2021 by Rightware. All rights reserved.

/// Subsystems and base classes should go here
#ifndef KZ_KANZI_BASE_HPP
#define KZ_KANZI_BASE_HPP

#include <kanzi/core.ui/action/action.hpp>
#include <kanzi/core.ui/action/dispatch_message_action.hpp>
#include <kanzi/core.ui/action/forwarding_action.hpp>
#include <kanzi/core.ui/action/play_animation_action.hpp>
#include <kanzi/core.ui/action/set_property_action.hpp>
#include <kanzi/core.ui/animation/from_to_animation.hpp>
#include <kanzi/core.ui/animation/keyframe_animation.hpp>
#include <kanzi/core.ui/animation/parallel_timeline.hpp>
#include <kanzi/core.ui/animation/property_animation_timeline.hpp>
#include <kanzi/core.ui/animation/property_field_animation_timeline.hpp>
#include <kanzi/core.ui/animation/scenegraph_timeline_playback_context.hpp>
#include <kanzi/core.ui/animation/sequential_timeline.hpp>
#include <kanzi/core.ui/animation/timeline_clock.hpp>
#include <kanzi/core.ui/animation/timeline_playback.hpp>
#include <kanzi/core.ui/application/kzu_engine.h>
#include <kanzi/core.ui/binding/animation_binding_processor.hpp>
#include <kanzi/core.ui/binding/binding.hpp>
#include <kanzi/core.ui/binding/binding_processor.hpp>
#include <kanzi/core.ui/binding/callback_processor.hpp>
#include <kanzi/core.ui/binding/expression_binding_processor.hpp>
#include <kanzi/core.ui/bitmap/bitmap_image.hpp>
#include <kanzi/core.ui/condition/condition.hpp>
#include <kanzi/core.ui/condition/expression_condition.hpp>
#include <kanzi/core.ui/constraints/constraints.hpp>
#include <kanzi/core.ui/content/binary_resource.hpp>
#include <kanzi/core.ui/content/content_item.hpp>
#include <kanzi/core.ui/content/content_item_collection.hpp>
#include <kanzi/core.ui/content/text_resource.hpp>
#include <kanzi/core.ui/data/data_object.hpp>
#include <kanzi/core.ui/data/data_object_list.hpp>
#include <kanzi/core.ui/data/data_source.hpp>
#include <kanzi/core.ui/domain/domain.hpp>
#include <kanzi/core/error/legacy_error.hpp>
#include <kanzi/core.ui/font/kzu_font.h>
#include <kanzi/core.ui/graphics2d/brush.hpp>
#include <kanzi/core.ui/graphics2d/brush_renderer.hpp>
#include <kanzi/core.ui/graphics2d/color_brush.hpp>
#include <kanzi/core.ui/graphics2d/color_brush_renderer.hpp>
#include <kanzi/core.ui/graphics2d/texture_brush.hpp>
#include <kanzi/core.ui/graphics2d/texture_brush_renderer.hpp>
#include <kanzi/core.ui/graphics3d/gpu_resource.hpp>
#include <kanzi/core.ui/graphics3d/material.hpp>
#include <kanzi/core.ui/graphics3d/material_brush.hpp>
#include <kanzi/core.ui/graphics3d/mesh.hpp>
#include <kanzi/core.ui/graphics3d/mesh_create_info.hpp>
#include <kanzi/core.ui/graphics3d/render_pass.hpp>
#include <kanzi/core.ui/graphics3d/draw_objects_render_pass.hpp>
#include <kanzi/core.ui/graphics3d/composition_target_render_pass.hpp>
#include <kanzi/core.ui/graphics3d/blit_render_pass.hpp>
#include <kanzi/core.ui/graphics3d/clear_render_pass.hpp>
#include <kanzi/core.ui/graphics3d/standard_material.hpp>
#include <kanzi/core.ui/graphics3d/tag.hpp>
#include <kanzi/core.ui/input/click_manipulator.hpp>
#include <kanzi/core.ui/input/drag_and_drop_manipulator.hpp>
#include <kanzi/core.ui/input/input_manipulator.hpp>
#include <kanzi/core.ui/input/keyboard.hpp>
#include <kanzi/core.ui/input/long_press_manipulator.hpp>
#include <kanzi/core.ui/input/multi_click_manipulator.hpp>
#include <kanzi/core.ui/input/pan_manipulator.hpp>
#include <kanzi/core.ui/input/pinch_manipulator.hpp>
#include <kanzi/core.ui/message/message_arguments.hpp>
#include <kanzi/core.ui/object/object.hpp>
#include <kanzi/core.ui/platform/graphics_backend/gl/framebuffer.hpp>
#include <kanzi/core.ui/platform/graphics_backend/gl/material_brush_renderer.hpp>
#include <kanzi/core.ui/platform/graphics_backend/gl/renderbuffer.hpp>
#include <kanzi/core.ui/platform/graphics_backend/gl/renderer3d.hpp>
#include <kanzi/core.ui/platform/graphics_backend/gl/sampler.hpp>
#include <kanzi/core.ui/platform/graphics_backend/gl/shader.hpp>
#include <kanzi/core.ui/platform/graphics_backend/gl/shader_create_info.hpp>
#include <kanzi/core.ui/platform/graphics_backend/gl/surface.hpp>
#include <kanzi/core.ui/platform/graphics_backend/gl/texture.hpp>
#include <kanzi/core.ui/platform/graphics_backend/gl/texture_create_info.hpp>
#include <kanzi/core.ui/property/variant.hpp>
#include <kanzi/core.ui/resource/collect_resource_urls.hpp>
#include <kanzi/core.ui/resource/resource.hpp>
#include <kanzi/core.ui/resource/resource_dictionary.hpp>
#include <kanzi/core.ui/resource/resource_manager.hpp>
#include <kanzi/core.ui/resource/trajectory.hpp>
#include <kanzi/core.ui/scheduler/kzu_task_scheduler.h>
#include <kanzi/core.ui/state_manager/state_manager.hpp>
#include <kanzi/core.ui/style/style.hpp>
#include <kanzi/core.ui/template/prefab.hpp>
#include <kanzi/core.ui/trigger/on_attached_trigger.hpp>
#include <kanzi/core.ui/trigger/on_property_changed_trigger.hpp>
#include <kanzi/core.ui/trigger/timer_trigger.hpp>
#include <kanzi/core.ui/trigger/trigger.hpp>

#include <kanzi/core/cpp/atomic.hpp>
#include <kanzi/core/cpp/condition_variable.hpp>
#include <kanzi/core/cpp/fstream.hpp>
#include <kanzi/core/cpp/memory.hpp>
#include <kanzi/core/cpp/mutex.hpp>
#include <kanzi/core/cpp/platform.hpp>
#include <kanzi/core/cpp/random.hpp>
#include <kanzi/core/cpp/thread.hpp>
#include <kanzi/core/error/exception.hpp>
#include <kanzi/core/message/message_type.hpp>
#include <kanzi/core/metadata/metaclass.hpp>
#include <kanzi/core/file/file_util.hpp>
#include <kanzi/core/metadata/meta_object_factory.hpp>
#include <kanzi/core/file/read_only_disk_file.hpp>
#include <kanzi/core/message/dynamic_message_type.hpp>
#include <kanzi/core/property/property_data_type.hpp>
#include <kanzi/core/property/property_field.hpp>
#include <kanzi/core/property/property_type.hpp>
#include <kanzi/core/property/resource_id.hpp>
#include <kanzi/core/legacy/file/kzs_file_base.hpp>
#include <kanzi/core/legacy/memory/kzc_memory_system.hpp>
#include <kanzi/core/legacy/thread/kzs_thread.hpp>
#include <kanzi/core/legacy/util/io/kzc_file.hpp>
#include <kanzi/core/math/color_rgba.hpp>
#include <kanzi/core/math/matrix3x3.hpp>
#include <kanzi/core/math/matrix4x4.hpp>
#include <kanzi/core/math/srt_value_2d.hpp>
#include <kanzi/core/math/srt_value_3d.hpp>
#include <kanzi/core/math/vector2.hpp>
#include <kanzi/core/math/vector3.hpp>
#include <kanzi/core/math/vector4.hpp>
#include <kanzi/core/module/module.hpp>
#include <kanzi/core/module/plugin.hpp>

#endif
